/**
 * Remove ALL patients (and reset the file-number counter for the current year).
 * Useful for clearing bulk test data generated by seed-patients.ts.
 *
 *   npm run db:clear:patients
 *
 * This does NOT touch the lookup tables (governorates, areas, nationalities),
 * the doctor account, or the audit log. It only clears the Patient table.
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const before = await prisma.patient.count();
  if (before === 0) {
    console.log('No patients to remove.');
    return;
  }

  const { count } = await prisma.patient.deleteMany({});

  // Reset this year's file-number sequence so new patients start from 0001 again.
  const year = new Date().getFullYear();
  await prisma.counter.deleteMany({ where: { key: `patient-file:${year}` } });

  console.log(`Removed ${count.toLocaleString()} patients and reset the ${year} file-number counter.`);
}

main()
  .catch((e) => {
    console.error('Clear failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
